name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-driver
    steps:
      - uses: actions/checkout@v3
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test

  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rl_agent
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest